// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ocmms.cmms.model.loto;

import com.ocmms.cmms.model.edm.Document;
import com.ocmms.cmms.model.edm.ImageDocument;
import com.ocmms.cmms.model.loto.LotoIssueReport;
import io.springlets.format.EntityFormat;
import javax.persistence.Entity;
import javax.persistence.Table;
import org.springframework.util.Assert;

privileged aspect LotoIssueReport_Roo_Jpa_Entity {
    
    declare @type: LotoIssueReport: @Entity;
    
    declare @type: LotoIssueReport: @Table(name = "LOTO_ISSUEREPORT");
    
    declare @type: LotoIssueReport: @EntityFormat(message = "entity_format_message_loto_issuereport");
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String LotoIssueReport.ITERABLE_TO_ADD_CANT_BE_NULL_MESSAGE = "The given Iterable of items to add can't be null!";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String LotoIssueReport.ITERABLE_TO_REMOVE_CANT_BE_NULL_MESSAGE = "The given Iterable of items to add can't be null!";
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param documentsToAdd
     */
    public void LotoIssueReport.addToDocuments(Iterable<Document> documentsToAdd) {
        Assert.notNull(documentsToAdd, ITERABLE_TO_ADD_CANT_BE_NULL_MESSAGE);
        for (Document item : documentsToAdd) {
            this.documents.add(item);
            item.setLotoIssueReport(this);
        }
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param documentsToRemove
     */
    public void LotoIssueReport.removeFromDocuments(Iterable<Document> documentsToRemove) {
        Assert.notNull(documentsToRemove, ITERABLE_TO_REMOVE_CANT_BE_NULL_MESSAGE);
        for (Document item : documentsToRemove) {
            this.documents.remove(item);
            item.setLotoIssueReport(null);
        }
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param imagesToAdd
     */
    public void LotoIssueReport.addToImages(Iterable<ImageDocument> imagesToAdd) {
        Assert.notNull(imagesToAdd, ITERABLE_TO_ADD_CANT_BE_NULL_MESSAGE);
        for (ImageDocument item : imagesToAdd) {
            this.images.add(item);
            item.setLotoIssueReport(this);
        }
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param imagesToRemove
     */
    public void LotoIssueReport.removeFromImages(Iterable<ImageDocument> imagesToRemove) {
        Assert.notNull(imagesToRemove, ITERABLE_TO_REMOVE_CANT_BE_NULL_MESSAGE);
        for (ImageDocument item : imagesToRemove) {
            this.images.remove(item);
            item.setLotoIssueReport(null);
        }
    }
    
}
