
# ===============================
# = DATA SOURCE
# ===============================
#spring.datasource.jndi-name=java:comp/env/jdbc/ocmmsDataSource
# Set here configurations for the database connection
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url = jdbc\:hsqldb\:file\:C\:\\ocmms\\ocmmsdb
#spring.datasource.url=jdbc:hsqldb:hsql://localhost/cmmsvc
#spring.datasource.driverClassName =org.hsqldb.jdbcDriver
#spring.datasource.url=jdbc:mysql://www.ocmms.com:3306/ocmmswxr
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/cmmsdev
#spring.datasource.url=jdbc:mysql://www.ocmms.com:3306/cmmsdev
# MySQL: Username and password
spring.datasource.username=sa
spring.datasource.password=120120
# ===============================
# = JPA / HIBERNATE
# ===============================
# Use spring.jpa.properties.* for Hibernate native properties (the prefix is
# stripped before adding them to the entity manager).
# Show or not log for each sql query
spring.jpa.show-sql=false
# Hibernate ddl auto (create, create-drop, update): with "update" the database
# schema will be automatically updated accordingly to java entities found in
# the project
#spring.jpa.hibernate.ddl-auto=update
# Naming strategy
#spring.jpa.hibernate.naming.strategy=org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# Allows Hibernate to generate SQL optimized for a particular DBMS
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.HSQLDialect
spring.jpa.properties.hibernate.id.new_generator_mappings=true
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

#JPA
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=false
spring.liquibase.drop-first=false
spring.liquibase.contexts=dev,prod

spring.liquibase.url=jdbc:mysql://localhost:3306/cmmsdev
spring.liquibase.user=sa
spring.liquibase.password=120120
#spring.liquibase.driver=com.mysql.cj.jdbc.Driver
#spring.liquibase.outputChangeLogFile=src/main/resources/db/changelog/db.changelog-master.yaml
#spring.liquibase.change-log=classpath:dbchangelog.xml
#referenceUrl=hibernate:spring:com.ocmms.cmms.data?dialect=org.hibernate.dialect.MySQLDialect
#spring.liquibase.referenceUrl=hibernate:spring:com.ocmms.cmms?dialect=org.hibernate.dialect.MySQL5Dialect&hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy&hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

# App Properties
bezkoder.app.jwtSecret= bezKoderSecretKey
bezkoder.app.jwtExpirationMs= 86400000
# ===============================
# = SSL
# ===============================
server.port=8080
#server.ssl.key-store=classpath:a.jks
#server.ssl.key-store-provider=SUN
#server.ssl.key-store-type=JKS
#server.port=443
#server.ssl.enabled=true
#server.ssl.key-password=mGYD65MU
#server.ssl.key-store-password=mGYD65MU
# ===============================
# = MAIL RECEIVER
# ===============================
springlets.mail.receiver.host=
springlets.mail.receiver.jndi-name=
springlets.mail.receiver.password=
springlets.mail.receiver.port=
springlets.mail.receiver.protocol=
springlets.mail.receiver.starttls-enable=
springlets.mail.receiver.username=
# ===============================
# = File Upload CFG
# ===============================
ocmms.fileupload.fileLocation=c\:\\uploadDir\\
ocmms.fileupload.image.height=120
ocmms.fileupload.image.newFormat=png
ocmms.fileupload.image.width=120
# ===============================
# = App Common CFG
# ===============================
spring.application.name=OCMMS
# ===============================
# = App WeChat CFG
# ===============================
wx.miniapp.aesKey=s6bD5EUMqeEK4HwiLnF6vrFMauAzY9jctoEpV79fbKU
wx.miniapp.appid=wx0abc7d1c6c46aba9
wx.miniapp.encrypt=x2KFMlFga5K83DXGrwW58bgrPbElFbpJxvvsApBact0
wx.miniapp.grant_type=authorization_code
wx.miniapp.jscode2session_url=https\://api.weixin.qq.com/sns/jscode2session
wx.miniapp.key=011AYj490AE0qF1tNT390AWd490AYj4r
wx.miniapp.msg-data-format=JSON
wx.miniapp.secret=464a7552da15460cb89b7d8e99e76073
wx.miniapp.token=464a7552da15460cb89b7d8e99e76073
# ===============================
# = App JasperReport CFG
# ===============================
ocmms.report.template.path=c\:\\report\\
ocmms.report.template.equipment=export_assetbarcode_default.jrxml
ocmms.report.template.storagelocation=export_binlocationdetail_default.jrxml
ocmms.report.template.podetail=export_podetail_default.jrxml
ocmms.report.template.pomaterialdetail=export_pomaterialdetail_default.jrxml
ocmms.report.template.storageLogcation=export_binlocationdetail_default.jrxml
ocmms.report.template.equipmaintenance=export_maintainbarcode_default.jrxml
ocmms.report.template.partmaintenance=export_maintainbarcode_default.jrxml
ocmms.report.template.lotoreport=export_loto_report.jrxml
ocmms.report.template.lotodetail=export_loto_detail.jrxml
# ===============================
# = App mail template CFG
# ===============================
spring.mail.task.notification.newtask=mail_newtask_notification
spring.mail.task.notification.complete=mail_taskcomplete_notification
spring.mail.materialstock.notification.low=mail_materialstock_low_notification
spring.mail.materialstock.notification.lowweek=mail_materialstock_low_week_notification
spring.mail.materialstock.notification.newinstock=mail_materialstock_newinstock_notification

spring.mail.task.complete.receivers=
# ===============================
# = App BATCH CFG
# ===============================
spring.batch.job.enabled=false
spring.main.banner-mode=off
 
#batch input files location
spring.application.upload.savefilepath=c:/temp/input
spring.servlet.multipart.max-file-size = 10MB
spring.servlet.multipart.max-request-size=100MB
# ===============================
# = MAIL CFG
# ===============================
spring.mail.default-encoding=UTF-8
spring.mail.host=smtp.mxhichina.com
spring.mail.username=info@ocmms.com
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.port=465
spring.mail.protocol=smtp
spring.messages.encoding=ISO-8859-1
mail.from.address=info@ocmms.com

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.packagesToScan=com.ocmms.cmms

spring.data.rest.basePath=/api

