url=jdbc:mysql://localhost:3306/cmmsdev
username=sa
password=120120
driver=com.mysql.cj.jdbc.Driver
outputChangeLogFile=src/main/resources/db/changelog/db.changelog-master.yaml
#changeLogFile=dbchangelog.xml
#outputChangeLogFile=classpath:dbchangelog.xml
#referenceUrl=hibernate:spring:com.ocmms.cmms.data?dialect=org.hibernate.dialect.MySQLDialect
referenceUrl=hibernate:spring:com.ocmms.cmms?dialect=org.hibernate.dialect.MySQL5Dialect&hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy&hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
