# HSQL JDBC Connector Configuration
#dataSource.driverClassName=org.hsqldb.jdbcDriver
#dataSource.url=jdbc:hsqldb:mem:test
#dataSource.username=sa
#dataSource.password=

#hibernate.dialect=org.hibernate.dialect.HSQLDialect
#hibernate.hbm2ddl.auto=create
#hibernate.show_sql=true
#hibernate.format_sql=true
#hibernate.use_sql_comments=true

# Mysql JDBC Connector Configuration
dataSource.driverClassName=com.mysql.jdbc.Driver
dataSource.url=jdbc\:mysql\://127.0.0.1\:3306/ocmms?useLegacyDatetimeCode=false&serverTimezone=UTC
dataSource.username=700001280
dataSource.password=120120

hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
hibernate.hbm2ddl.auto=create
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.use_sql_comments=true