package com.ocmms.cmms.model.pm.notification;

import com.ocmms.cmms.model.system.RecordStatus;
import io.springlets.format.EntityFormat;
import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.roo.addon.javabean.annotations.RooEquals;
import org.springframework.roo.addon.javabean.annotations.RooJavaBean;
import org.springframework.roo.addon.javabean.annotations.RooSerializable;
import org.springframework.roo.addon.javabean.annotations.RooToString;
import org.springframework.roo.addon.jpa.annotations.audit.RooJpaAudit;
import org.springframework.roo.addon.jpa.annotations.entity.JpaRelationType;
import org.springframework.roo.addon.jpa.annotations.entity.RooJpaEntity;
import org.springframework.roo.addon.jpa.annotations.entity.RooJpaRelation;

/**
 * The user status of the notification will be used to indicate the current
 * status of the notification record. This will be a status that is set manually
 * by the user and not the system.
 * 
 * @author qinzeyong
 *
 */

@RooJavaBean
@RooToString
@RooJpaEntity(table = "PM_NOTIFICATION_USERSTATUSWITHNUMBER", entityFormatMessage = "entity_format_message_pm_notification_userstatuswithnumber")
@RooEquals(isJpaEntity = true)
@RooSerializable
@RooJpaAudit
public class NotificationUserStatusWithNumber {

	/**
	 * Auto Generation by System
	 * 
	 */
	@Id
	@SequenceGenerator(name = "NotificationUserStatusWithNumberGen", sequenceName = "SEQ_PM_NOTIFICATION_USERSTATUSWITHNUMBER_ID")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "NotificationUserStatusWithNumberGen")
	@Column(name = "ID")
	private Long id;

	
	@NotNull
	@Column(name = "CODE")
	@Size(max = 50)
	private String code;

	/**
	 * Outstanding Postponed In process Completed
	 */
	@NotNull
	@Column(name = "DESCRIPTION")
	private String description;

	/**
	 * TODO Auto-generated attribute documentation
	 *
	 */
	@OneToMany(cascade = { javax.persistence.CascadeType.MERGE,
			javax.persistence.CascadeType.PERSIST }, fetch = FetchType.LAZY, mappedBy = "userStatus")
	@RooJpaRelation(type = JpaRelationType.AGGREGATION)
	private Set<NotificationHeader> notificationHeaders = new HashSet<NotificationHeader>();

	/**** General Information Generated By System Start ****/

        /**
	 * TODO Auto-generated attribute documentation
	 *
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RECORDSTATUS")
	@EntityFormat
	private RecordStatus recordStatus;
        
	/**
	 * record version, while changed or updated should be plus one;
	 *
	 */
	@Version
	@Column(name = "VERSION")
	private Long version;

	/**
	 * record created date, while created record this filed will be set;
	 *
	 */
	@Column(name = "CREATED_DATE")
	@Temporal(TemporalType.TIMESTAMP)
	@DateTimeFormat(style = "M-")
	@CreatedDate
	private Calendar createdDate;

	/**
	 * record created user, while created record this filed will be set;
	 *
	 */
	@Column(name = "CREATED_BY")
	@CreatedBy
	private String createdBy;

	/**
	 * record update date, while update record this filed will be set;
	 *
	 */
	@Column(name = "LASTMODIFIED_DATE")
	@Temporal(TemporalType.TIMESTAMP)
	@DateTimeFormat(style = "M-")
	@LastModifiedDate
	private Calendar lastModifiedDate;

	/**
	 * Record last update user, while last update record this filed will be set;
	 *
	 */
	@Column(name = "LASTMODIFIED_BY")
	@LastModifiedBy
	private String lastModifiedBy;
	/**** General Information Generated By System End ******/
}
