package com.ocmms.cmms.model.pm.notification;

import com.ocmms.cmms.model.system.RecordStatus;
import io.springlets.format.EntityFormat;
import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.roo.addon.javabean.annotations.RooEquals;
import org.springframework.roo.addon.javabean.annotations.RooJavaBean;
import org.springframework.roo.addon.javabean.annotations.RooSerializable;
import org.springframework.roo.addon.javabean.annotations.RooToString;
import org.springframework.roo.addon.jpa.annotations.audit.RooJpaAudit;
import org.springframework.roo.addon.jpa.annotations.entity.RooJpaEntity;

/**
 * The user status of the notification will be used to indicate the current
 * status of the notification record. This will be a status that is set manually
 * by the user and not the system.
 * 
 * 
 * H-00 = Hold <br>
 * H-10 = Held for information <br>
 * H-20 = Equip. not available <br>
 * H-30 = Held for approval <br>
 * H-40 = Held for engineering <br>
 * H-50 = Held for inspection <br>
 * H-60 = Hold for TA Gate keeper <br>
 * H-70 = Approved for TA gate keeping <br>
 * RJC1 = Rejected –not Like for Like <br>
 * RJC2 = Rejected – No value added <br>
 * RJC3 = Rejected -Duplicate<br>
 * 
 * @author qinzeyong
 *
 */

@RooJavaBean
@RooToString
@RooJpaEntity(table = "PM_NOTIFICATION_USERSTATUSWITHOUTNUMBER", entityFormatMessage = "entity_format_message_pm_notification_userstatuswithoutnumber")
@RooEquals(isJpaEntity = true)
@RooSerializable
@RooJpaAudit
public class NotificationUserStatusWithoutNumber {

	/**
	 * Type: Long <br>
	 * database id<br>
	 * Auto Generation by System
	 * 
	 * @author qinzeyong
	 * @since 3.0.0.0
	 */
	@Id
	@SequenceGenerator(name = "NotificationUserStatusWithoutNumberGen", sequenceName = "SEQ_PM_NOTIFICATION_USERSTATUSWITHOUTNUMBER_ID")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "NotificationUserStatusWithoutNumberGen")
	@Column(name = "ID")
	private Long id;

	@NotNull
	@Column(name = "CODE")
	@Size(max = 50)
	private String code;

	/**
	 * Outstanding Postponed In process Completed
	 */
	@NotNull
	@Column(name = "DESCRIPTION")
	private String description;

	/**
	 * TODO Auto-generated attribute documentation
	 *
	 */
	@ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinTable(name = "NW_NOTIFICATION_USERSTATUSES", joinColumns = {
			@JoinColumn(name = "USERSTATUS_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "NOTIFICATION_ID", nullable = false, updatable = false) })
	private Set<NotificationHeader> notificationHeaders = new HashSet<NotificationHeader>();

	/**** General Information Generated By System Start ****/

        /**
	 * TODO Auto-generated attribute documentation
	 *
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RECORDSTATUS")
	@EntityFormat
	private RecordStatus recordStatus;
        
	/**
	 * record version, while changed or updated should be plus one;
	 *
	 */
	@Version
	@Column(name = "VERSION")
	private Long version;

	/**
	 * record created date, while created record this filed will be set;
	 *
	 */
	@Column(name = "CREATED_DATE")
	@Temporal(TemporalType.TIMESTAMP)
	@DateTimeFormat(style = "M-")
	@CreatedDate
	private Calendar createdDate;

	/**
	 * record created user, while created record this filed will be set;
	 *
	 */
	@Column(name = "CREATED_BY")
	@CreatedBy
	private String createdBy;

	/**
	 * record update date, while update record this filed will be set;
	 *
	 */
	@Column(name = "LASTMODIFIED_DATE")
	@Temporal(TemporalType.TIMESTAMP)
	@DateTimeFormat(style = "M-")
	@LastModifiedDate
	private Calendar lastModifiedDate;

	/**
	 * Record last update user, while last update record this filed will be set;
	 *
	 */
	@Column(name = "LASTMODIFIED_BY")
	@LastModifiedBy
	private String lastModifiedBy;
	/**** General Information Generated By System End ******/

}
