package com.ocmms.cmms.model.pm.workorder;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.ocmms.cmms.model.system.RecordStatus;
import lombok.Data;
import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Objects;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Table;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * = WorkOrderSystemStatus TODO Auto-generated class documentation
 *
 */
@Data

@EntityListeners(AuditingEntityListener.class)
@Entity
@Table(name = "PM_WORKORDER_SYSTEMSTATUS")
//@JsonIgnoreProperties({ "hibernateLazyInitializer" })
public class WorkOrderSystemStatus implements Serializable {

	/**
	 * Type: Long <br>
	 * database id<br>
	 * Auto Generation by System
	 *
	 * @author qinzeyong
	 * @since 3.0.0.0
	 */
	@Id
	@SequenceGenerator(name = "WorkOrderSystemStatusGen", sequenceName = "SEQ_PM_WORKORDER_SYSTEMSTATUS_ID")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "WorkOrderSystemStatusGen")
	@Column(name = "ID")
	private Long id;

	/**
	 *
	 */
	@NotNull
	@Column(name = "CODE")
	@Size(max = 50)
	private String code;

	/**
	 * Outstanding Postponed In process Completed
	 */
	@NotNull
	@Column(name = "DESCRIPTION")
	private String description;

	/**
	 * TODO Auto-generated attribute documentation
	 *
	 */
	@ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinTable(name = "NW_WORKORDER_SYSTEMSTATUS", joinColumns = {
			@JoinColumn(name = "SYSTEMSTATUS_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "WORKORDER_ID", nullable = false, updatable = false) })
	private Set<WorkOrderHeader> workOrderHeaders = new HashSet<WorkOrderHeader>();

	/**** General Information Generated By System Start ****/
	/**
	 * TODO Auto-generated attribute documentation
	 *
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RECORDSTATUS")

	private RecordStatus recordStatus;

	/**
	 * record version, while changed or updated should be plus one;
	 *
	 */
	@Version
	@Column(name = "VERSION")
	private Long version;

	/**
	 * record created date, while created record this filed will be set;
	 *
	 */
	@Column(name = "CREATED_DATE")
	@Temporal(TemporalType.TIMESTAMP)
	@DateTimeFormat(style = "M-")
	@CreatedDate
	private Calendar createdDate;

	/**
	 * record created user, while created record this filed will be set;
	 *
	 */
	@Column(name = "CREATED_BY")
	@CreatedBy
	private String createdBy;

	/**
	 * record update date, while update record this filed will be set;
	 *
	 */
	@Column(name = "LASTMODIFIED_DATE")
	@Temporal(TemporalType.TIMESTAMP)
	@DateTimeFormat(style = "M-")
	@LastModifiedDate
	private Calendar lastModifiedDate;

	/**
	 * Record last update user, while last update record this filed will be set;
	 *
	 */
	@Column(name = "LASTMODIFIED_BY")
	@LastModifiedBy
	private String lastModifiedBy;

	/**
	 * TODO Auto-generated attribute documentation
	 *
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * TODO Auto-generated attribute documentation
	 *
	 */
	public static final String ITERABLE_TO_ADD_CANT_BE_NULL_MESSAGE = "The given Iterable of items to add can't be null!";

	/**
	 * TODO Auto-generated attribute documentation
	 *
	 */
	public static final String ITERABLE_TO_REMOVE_CANT_BE_NULL_MESSAGE = "The given Iterable of items to add can't be null!";

	

	/**
	 * This `equals` implementation is specific for JPA entities and uses the entity
	 * identifier for it, following the article in
	 * https://vladmihalcea.com/2016/06/06/how-to-implement-equals-and-hashcode-using-the-jpa-entity-identifier/
	 *
	 * @param obj
	 * @return Boolean
	 */
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		// instanceof is false if the instance is null
		if (!(obj instanceof WorkOrderSystemStatus)) {
			return false;
		}
		return getId() != null && Objects.equals(getId(), ((WorkOrderSystemStatus) obj).getId());
	}

	/**
	 * This `hashCode` implementation is specific for JPA entities and uses a fixed
	 * `int` value to be able to identify the entity in collections after a new id
	 * is assigned to the entity, following the article in
	 * https://vladmihalcea.com/2016/06/06/how-to-implement-equals-and-hashcode-using-the-jpa-entity-identifier/
	 *
	 * @return Integer
	 */
	public int hashCode() {
		return 31;
	}

	/**
	 * TODO Auto-generated method documentation
	 *
	 * @return String
	 */
	public String toString() {
		return "WorkOrderSystemStatus {" + "id='" + id + '\'' + ", code='" + code + '\'' + ", description='"
				+ description + '\'' + ", version='" + version + '\'' + ", createdDate='" + createdDate == null
						? null
						: java.text.DateFormat.getDateTimeInstance().format(createdDate.getTime()) + '\''
								+ ", createdBy='" + createdBy + '\'' + ", lastModifiedDate='" + lastModifiedDate == null
										? null
										: java.text.DateFormat.getDateTimeInstance().format(lastModifiedDate.getTime())
												+ '\'' + ", lastModifiedBy='" + lastModifiedBy + '\'' + "}"
												+ super.toString();
	}
}
