package com.ocmms.cmms.model.mm.master;

import org.springframework.roo.addon.javabean.annotations.RooEquals;
import org.springframework.roo.addon.javabean.annotations.RooJavaBean;
import org.springframework.roo.addon.javabean.annotations.RooSerializable;
import org.springframework.roo.addon.javabean.annotations.RooToString;
import org.springframework.roo.addon.jpa.annotations.audit.RooJpaAudit;
import org.springframework.roo.addon.jpa.annotations.entity.JpaRelationType;
import org.springframework.roo.addon.jpa.annotations.entity.RooJpaEntity;
import org.springframework.roo.addon.jpa.annotations.entity.RooJpaRelation;

import com.ocmms.cmms.model.hrm.Organization;
import com.ocmms.cmms.model.hrm.Plant;
import com.ocmms.cmms.model.mm.storage.MaterialInstockDetail;
import com.ocmms.cmms.model.mm.storage.MaterialOutstockDetail;
import com.ocmms.cmms.model.mm.storage.StorageLocation;

import io.springlets.format.EntityFormat;
import java.math.BigDecimal;
import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;
import com.ocmms.cmms.model.pm.routine.PartScrappingRecord;
import com.ocmms.cmms.model.system.RecordStatus;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.NumberFormat;

/**
 * = MaterialPlantInfo TODO Auto-generated class documentation
 *
 */
@RooJavaBean
@RooToString
@RooJpaEntity(inheritanceType = "SINGLE_TABLE", table = "MM_MASTER_MATERIALPLANTINFO", entityFormatMessage = "entity_format_message_mm_master_materialplantinfo")
@RooEquals(isJpaEntity = true)
@RooSerializable
@RooJpaAudit
public class MaterialPlantInfo {

	/**
	 * TODO Auto-generated attribute documentation
	 *
	 */
	@Id
	@SequenceGenerator(name = "materialPlantInfoGen", sequenceName = "SEQ_MM_MASTER_MATERIALPLANTINFO_ID")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "materialPlantInfoGen")
	@Column(name = "ID")
	private Long id;

	/**
	 * TODO Auto-generated attribute documentation
	 *
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MATERIALCATALOG")
	@EntityFormat
	private MaterialCatalog materialCatalog;

	/**
	 * TODO Auto-generated attribute documentation
	 *
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PLANT")
	@EntityFormat
	private Plant plant;

	/**
	 * TODO Auto-generated attribute documentation
	 *
	 */
	@Column(name = "STOCK", columnDefinition = "Decimal(10,2) default '0.00'")
	@NumberFormat
	private BigDecimal stock;

	/**
	 * TODO Auto-generated attribute documentation
	 *
	 */
	@Column(name = "SAFETYSTOCK", columnDefinition = "Decimal(10,2) default '0.00'")
	@NumberFormat
	private BigDecimal safetyStock;

	/**
	 * TODO Auto-generated attribute documentation
	 *
	 */
	@Column(name = "REQREORDERPOINT", columnDefinition = "Decimal(10,2) default '0.00'")
	@NumberFormat
	private BigDecimal reqReorderPoint;

	/**
	 * TODO Auto-generated attribute documentation
	 *
	 */
	@Column(name = "CONSUMABLEINVENTORY")
	private Boolean consumableInventory;

	/**
	 * TODO Auto-generated attribute documentation
	 *
	 */
	@Column(name = "CRITICAL")
	private Boolean critical;

	/**
	 * TODO Auto-generated attribute documentation
	 *
	 */
	@Column(name = "USEFULLIFE")	
	private Boolean usefulLife;
	
	/**
	 * TODO Auto-generated attribute documentation
	 *
	 */
	@Column(name = "SHELFLIFEDAYS")
	@NumberFormat
	private Integer shelfLifeDays;

	
	/**
	 * TODO Auto-generated attribute documentation
	 *
	 */
	@Column(name = "DECLARATIONNUMBER")
	private String declarationNumber;

	/**
	 * TODO Auto-generated attribute documentation
	 *
	 */
	@Column(name = "DECLARATIONNAME")
	private String declarationName;

	/**
	 * TODO Auto-generated attribute documentation
	 *
	 */
	@Column(name = "DOCUMENTTYPE")
	private String documentType;

	
	/**** General Information Generated By System Start ****/
	
        /**
	 * TODO Auto-generated attribute documentation
	 *
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RECORDSTATUS")
	@EntityFormat
	private RecordStatus recordStatus;
        
        /**
	 * record version, while changed or updated should be plus one;
	 *
	 */
	@Version
	@Column(name = "VERSION")
	private Long version;

	/**
	 * record created date, while created record this filed will be set;
	 *
	 */
	@Column(name = "CREATED_DATE")
	@Temporal(TemporalType.TIMESTAMP)
	@DateTimeFormat(style = "M-")
	@CreatedDate
	private Calendar createdDate;

	/**
	 * record created user, while created record this filed will be set;
	 *
	 */
	@Column(name = "CREATED_BY")
	@CreatedBy
	private String createdBy;

	/**
	 * record update date, while update record this filed will be set;
	 *
	 */
	@Column(name = "LASTMODIFIED_DATE")
	@Temporal(TemporalType.TIMESTAMP)
	@DateTimeFormat(style = "M-")
	@LastModifiedDate
	private Calendar lastModifiedDate;

	/**
	 * Record last update user, while last update record this filed will be set;
	 *
	 */
	@Column(name = "LASTMODIFIED_BY")
	@LastModifiedBy
	private String lastModifiedBy;
	/**** General Information Generated By System End ******/
}
