// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ocmms.cmms.repository;

import com.ocmms.cmms.model.pm.routine.PartScrappingRecord;
import com.ocmms.cmms.repository.PartScrappingOutstockDetailRepository;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PartScrappingOutstockDetailRepository_Roo_Jpa_Repository {
    
    declare @type: PartScrappingOutstockDetailRepository: @Transactional(readOnly = true);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param partScrappingRecord
     * @return Long
     */
    public abstract long PartScrappingOutstockDetailRepository.countByPartScrappingRecord(PartScrappingRecord partScrappingRecord);
    
}
