// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ocmms.cmms.repository;

import com.ocmms.cmms.model.pm.pm.PreventiveMaintenanceStandard;
import com.ocmms.cmms.repository.PreventiveMaintenanceContentRepository;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PreventiveMaintenanceContentRepository_Roo_Jpa_Repository {
    
    declare @type: PreventiveMaintenanceContentRepository: @Transactional(readOnly = true);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param preventiveMaintenanceStandard
     * @return Long
     */
    public abstract long PreventiveMaintenanceContentRepository.countByPreventiveMaintenanceStandard(PreventiveMaintenanceStandard preventiveMaintenanceStandard);
    
}
