// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ocmms.cmms.repository;

import com.ocmms.cmms.repository.StorageTypeRepository;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StorageTypeRepository_Roo_Jpa_Repository {
    
    declare @type: StorageTypeRepository: @Transactional(readOnly = true);
    
}
