// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ocmms.cmms.web;

import com.ocmms.cmms.web.EquipmentsItemMeasuringRecordsThymeleafController;
import com.ocmms.cmms.web.EquipmentsItemMeasuringRecordsThymeleafLinkFactory;
import io.springlets.web.mvc.util.MethodLinkFactory;
import io.springlets.web.mvc.util.SpringletsMvcUriComponentsBuilder;
import java.util.Map;
import org.springframework.stereotype.Component;
import org.springframework.web.util.UriComponents;

privileged aspect EquipmentsItemMeasuringRecordsThymeleafLinkFactory_Roo_LinkFactory {
    
    declare parents: EquipmentsItemMeasuringRecordsThymeleafLinkFactory implements MethodLinkFactory<EquipmentsItemMeasuringRecordsThymeleafController>;
    
    declare @type: EquipmentsItemMeasuringRecordsThymeleafLinkFactory: @Component;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String EquipmentsItemMeasuringRecordsThymeleafLinkFactory.DATATABLES = "datatables";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String EquipmentsItemMeasuringRecordsThymeleafLinkFactory.DATATABLESBYIDSIN = "datatablesByIdsIn";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String EquipmentsItemMeasuringRecordsThymeleafLinkFactory.CREATEFORM = "createForm";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String EquipmentsItemMeasuringRecordsThymeleafLinkFactory.REMOVEFROMMEASURINGRECORDS = "removeFromMeasuringRecords";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String EquipmentsItemMeasuringRecordsThymeleafLinkFactory.REMOVEFROMMEASURINGRECORDSBATCH = "removeFromMeasuringRecordsBatch";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String EquipmentsItemMeasuringRecordsThymeleafLinkFactory.CREATE = "create";
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Class
     */
    public Class<EquipmentsItemMeasuringRecordsThymeleafController> EquipmentsItemMeasuringRecordsThymeleafLinkFactory.getControllerClass() {
        return EquipmentsItemMeasuringRecordsThymeleafController.class;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param methodName
     * @param parameters
     * @param pathVariables
     * @return UriComponents
     */
    public UriComponents EquipmentsItemMeasuringRecordsThymeleafLinkFactory.toUri(String methodName, Object[] parameters, Map<String, Object> pathVariables) {
        if (methodName.equals(DATATABLES)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).datatables(null, null, null, null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(DATATABLESBYIDSIN)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).datatablesByIdsIn(null, null, null, null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(CREATEFORM)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).createForm(null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(REMOVEFROMMEASURINGRECORDS)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).removeFromMeasuringRecords(null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(REMOVEFROMMEASURINGRECORDSBATCH)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).removeFromMeasuringRecordsBatch(null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(CREATE)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).create(null, null, null, null, null)).buildAndExpand(pathVariables);
        }
        throw new IllegalArgumentException("Invalid method name: " + methodName);
    }
    
}
