// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ocmms.cmms.web;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.ObjectCodec;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.ocmms.cmms.model.pm.routine.EquipmentScrappingRecord;
import com.ocmms.cmms.service.api.EquipmentScrappingRecordService;
import com.ocmms.cmms.web.EquipmentScrappingRecordDeserializer;
import io.springlets.web.NotFoundException;
import java.io.IOException;
import org.springframework.boot.jackson.JsonComponent;
import org.springframework.core.convert.ConversionService;

privileged aspect EquipmentScrappingRecordDeserializer_Roo_EntityDeserializer {
    
    declare @type: EquipmentScrappingRecordDeserializer: @JsonComponent;
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return EquipmentScrappingRecordService
     */
    public EquipmentScrappingRecordService EquipmentScrappingRecordDeserializer.getEquipmentScrappingRecordService() {
        return equipmentScrappingRecordService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param equipmentScrappingRecordService
     */
    public void EquipmentScrappingRecordDeserializer.setEquipmentScrappingRecordService(EquipmentScrappingRecordService equipmentScrappingRecordService) {
        this.equipmentScrappingRecordService = equipmentScrappingRecordService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return ConversionService
     */
    public ConversionService EquipmentScrappingRecordDeserializer.getConversionService() {
        return conversionService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param conversionService
     */
    public void EquipmentScrappingRecordDeserializer.setConversionService(ConversionService conversionService) {
        this.conversionService = conversionService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param jsonParser
     * @param context
     * @param codec
     * @param tree
     * @return EquipmentScrappingRecord
     * @throws IOException
     */
    public EquipmentScrappingRecord EquipmentScrappingRecordDeserializer.deserializeObject(JsonParser jsonParser, DeserializationContext context, ObjectCodec codec, JsonNode tree) throws IOException {
        String idText = tree.asText();
        Long id = conversionService.convert(idText, Long.class);
        EquipmentScrappingRecord equipmentScrappingRecord = equipmentScrappingRecordService.findOne(id);
        if (equipmentScrappingRecord == null) {
            throw new NotFoundException("EquipmentScrappingRecord not found");
        }
        return equipmentScrappingRecord;
    }
    
}
