// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ocmms.cmms.web;

import com.ocmms.cmms.web.MaterialCatalogsItemMaterialVendorInfosThymeleafController;
import com.ocmms.cmms.web.MaterialCatalogsItemMaterialVendorInfosThymeleafLinkFactory;
import io.springlets.web.mvc.util.MethodLinkFactory;
import io.springlets.web.mvc.util.SpringletsMvcUriComponentsBuilder;
import java.util.Map;
import org.springframework.stereotype.Component;
import org.springframework.web.util.UriComponents;

privileged aspect MaterialCatalogsItemMaterialVendorInfosThymeleafLinkFactory_Roo_LinkFactory {
    
    declare parents: MaterialCatalogsItemMaterialVendorInfosThymeleafLinkFactory implements MethodLinkFactory<MaterialCatalogsItemMaterialVendorInfosThymeleafController>;
    
    declare @type: MaterialCatalogsItemMaterialVendorInfosThymeleafLinkFactory: @Component;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String MaterialCatalogsItemMaterialVendorInfosThymeleafLinkFactory.DATATABLES = "datatables";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String MaterialCatalogsItemMaterialVendorInfosThymeleafLinkFactory.DATATABLESBYIDSIN = "datatablesByIdsIn";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String MaterialCatalogsItemMaterialVendorInfosThymeleafLinkFactory.CREATEFORM = "createForm";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String MaterialCatalogsItemMaterialVendorInfosThymeleafLinkFactory.REMOVEFROMMATERIALVENDORINFOS = "removeFromMaterialVendorInfos";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String MaterialCatalogsItemMaterialVendorInfosThymeleafLinkFactory.REMOVEFROMMATERIALVENDORINFOSBATCH = "removeFromMaterialVendorInfosBatch";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String MaterialCatalogsItemMaterialVendorInfosThymeleafLinkFactory.CREATE = "create";
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Class
     */
    public Class<MaterialCatalogsItemMaterialVendorInfosThymeleafController> MaterialCatalogsItemMaterialVendorInfosThymeleafLinkFactory.getControllerClass() {
        return MaterialCatalogsItemMaterialVendorInfosThymeleafController.class;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param methodName
     * @param parameters
     * @param pathVariables
     * @return UriComponents
     */
    public UriComponents MaterialCatalogsItemMaterialVendorInfosThymeleafLinkFactory.toUri(String methodName, Object[] parameters, Map<String, Object> pathVariables) {
        if (methodName.equals(DATATABLES)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).datatables(null, null, null, null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(DATATABLESBYIDSIN)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).datatablesByIdsIn(null, null, null, null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(CREATEFORM)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).createForm(null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(REMOVEFROMMATERIALVENDORINFOS)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).removeFromMaterialVendorInfos(null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(REMOVEFROMMATERIALVENDORINFOSBATCH)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).removeFromMaterialVendorInfosBatch(null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(CREATE)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).create(null, null, null, null, null)).buildAndExpand(pathVariables);
        }
        throw new IllegalArgumentException("Invalid method name: " + methodName);
    }
    
}
