// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ocmms.cmms.web;

import com.ocmms.cmms.web.ProcurementOrdersItemProcurementOrderFinanceTrackingsThymeleafController;
import com.ocmms.cmms.web.ProcurementOrdersItemProcurementOrderFinanceTrackingsThymeleafLinkFactory;
import io.springlets.web.mvc.util.MethodLinkFactory;
import io.springlets.web.mvc.util.SpringletsMvcUriComponentsBuilder;
import java.util.Map;
import org.springframework.stereotype.Component;
import org.springframework.web.util.UriComponents;

privileged aspect ProcurementOrdersItemProcurementOrderFinanceTrackingsThymeleafLinkFactory_Roo_LinkFactory {
    
    declare parents: ProcurementOrdersItemProcurementOrderFinanceTrackingsThymeleafLinkFactory implements MethodLinkFactory<ProcurementOrdersItemProcurementOrderFinanceTrackingsThymeleafController>;
    
    declare @type: ProcurementOrdersItemProcurementOrderFinanceTrackingsThymeleafLinkFactory: @Component;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String ProcurementOrdersItemProcurementOrderFinanceTrackingsThymeleafLinkFactory.DATATABLES = "datatables";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String ProcurementOrdersItemProcurementOrderFinanceTrackingsThymeleafLinkFactory.DATATABLESBYIDSIN = "datatablesByIdsIn";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String ProcurementOrdersItemProcurementOrderFinanceTrackingsThymeleafLinkFactory.CREATEFORM = "createForm";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String ProcurementOrdersItemProcurementOrderFinanceTrackingsThymeleafLinkFactory.REMOVEFROMPROCUREMENTORDERFINANCETRACKINGS = "removeFromProcurementOrderFinanceTrackings";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String ProcurementOrdersItemProcurementOrderFinanceTrackingsThymeleafLinkFactory.REMOVEFROMPROCUREMENTORDERFINANCETRACKINGSBATCH = "removeFromProcurementOrderFinanceTrackingsBatch";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String ProcurementOrdersItemProcurementOrderFinanceTrackingsThymeleafLinkFactory.CREATE = "create";
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Class
     */
    public Class<ProcurementOrdersItemProcurementOrderFinanceTrackingsThymeleafController> ProcurementOrdersItemProcurementOrderFinanceTrackingsThymeleafLinkFactory.getControllerClass() {
        return ProcurementOrdersItemProcurementOrderFinanceTrackingsThymeleafController.class;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param methodName
     * @param parameters
     * @param pathVariables
     * @return UriComponents
     */
    public UriComponents ProcurementOrdersItemProcurementOrderFinanceTrackingsThymeleafLinkFactory.toUri(String methodName, Object[] parameters, Map<String, Object> pathVariables) {
        if (methodName.equals(DATATABLES)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).datatables(null, null, null, null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(DATATABLESBYIDSIN)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).datatablesByIdsIn(null, null, null, null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(CREATEFORM)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).createForm(null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(REMOVEFROMPROCUREMENTORDERFINANCETRACKINGS)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).removeFromProcurementOrderFinanceTrackings(null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(REMOVEFROMPROCUREMENTORDERFINANCETRACKINGSBATCH)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).removeFromProcurementOrderFinanceTrackingsBatch(null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(CREATE)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).create(null, null, null, null, null)).buildAndExpand(pathVariables);
        }
        throw new IllegalArgumentException("Invalid method name: " + methodName);
    }
    
}
