// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ocmms.cmms.web;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.ocmms.cmms.model.hrm.Employee;
import com.ocmms.cmms.model.system.RecordStatus;
import com.ocmms.cmms.web.EmployeeDeserializer;
import com.ocmms.cmms.web.RecordStatusDeserializer;
import com.ocmms.cmms.web.ReportTemplateDefinitionJsonMixin;

privileged aspect ReportTemplateDefinitionJsonMixin_Roo_JSONMixin {
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @JsonDeserialize(using = EmployeeDeserializer.class)
    private Employee ReportTemplateDefinitionJsonMixin.Owner;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @JsonDeserialize(using = RecordStatusDeserializer.class)
    private RecordStatus ReportTemplateDefinitionJsonMixin.recordStatus;
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Employee
     */
    public Employee ReportTemplateDefinitionJsonMixin.getOwner() {
        return Owner;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param Owner
     */
    public void ReportTemplateDefinitionJsonMixin.setOwner(Employee Owner) {
        this.Owner = Owner;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return RecordStatus
     */
    public RecordStatus ReportTemplateDefinitionJsonMixin.getRecordStatus() {
        return recordStatus;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param recordStatus
     */
    public void ReportTemplateDefinitionJsonMixin.setRecordStatus(RecordStatus recordStatus) {
        this.recordStatus = recordStatus;
    }
    
}
