// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ocmms.cmms.web;

import com.ocmms.cmms.model.mm.master.ServiceCatalog;
import com.ocmms.cmms.service.api.ServiceCatalogService;
import com.ocmms.cmms.web.ServiceCatalogsCollectionJsonController;
import com.ocmms.cmms.web.ServiceCatalogsItemJsonController;
import io.springlets.data.domain.GlobalSearch;
import java.util.Collection;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.mvc.method.annotation.MvcUriComponentsBuilder;
import org.springframework.web.util.UriComponents;

privileged aspect ServiceCatalogsCollectionJsonController_Roo_JSON {
    
    declare @type: ServiceCatalogsCollectionJsonController: @RestController;
    
    declare @type: ServiceCatalogsCollectionJsonController: @RequestMapping(value = "/api/servicecatalogs", name = "ServiceCatalogsCollectionJsonController", produces = MediaType.APPLICATION_JSON_VALUE);
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private ServiceCatalogService ServiceCatalogsCollectionJsonController.serviceCatalogService;
    
    /**
     * TODO Auto-generated constructor documentation
     * 
     * @param serviceCatalogService
     */
    @Autowired
    public ServiceCatalogsCollectionJsonController.new(ServiceCatalogService serviceCatalogService) {
        this.serviceCatalogService = serviceCatalogService;
    }

    /**
     * TODO Auto-generated method documentation
     * 
     * @return ServiceCatalogService
     */
    public ServiceCatalogService ServiceCatalogsCollectionJsonController.getServiceCatalogService() {
        return serviceCatalogService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param serviceCatalogService
     */
    public void ServiceCatalogsCollectionJsonController.setServiceCatalogService(ServiceCatalogService serviceCatalogService) {
        this.serviceCatalogService = serviceCatalogService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param globalSearch
     * @param pageable
     * @return ResponseEntity
     */
    @GetMapping(name = "list")
    public ResponseEntity<Page<ServiceCatalog>> ServiceCatalogsCollectionJsonController.list(GlobalSearch globalSearch, Pageable pageable) {
        
        Page<ServiceCatalog> serviceCatalogs = getServiceCatalogService().findAll(globalSearch, pageable);
        return ResponseEntity.ok(serviceCatalogs);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return UriComponents
     */
    public static UriComponents ServiceCatalogsCollectionJsonController.listURI() {
        return MvcUriComponentsBuilder
            .fromMethodCall(
                MvcUriComponentsBuilder.on(ServiceCatalogsCollectionJsonController.class).list(null, null))
            .build().encode();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param serviceCatalog
     * @param result
     * @return ResponseEntity
     */
    @PostMapping(name = "create")
    public ResponseEntity<?> ServiceCatalogsCollectionJsonController.create(@Valid @RequestBody ServiceCatalog serviceCatalog, BindingResult result) {
        
        if (serviceCatalog.getId() != null || serviceCatalog.getVersion() != null) {        
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
        
        if (result.hasErrors()) {
            return ResponseEntity.status(HttpStatus.CONFLICT).body(result);
        }
        
        ServiceCatalog newServiceCatalog = getServiceCatalogService().save(serviceCatalog);
        UriComponents showURI = ServiceCatalogsItemJsonController.showURI(newServiceCatalog);
        
        return ResponseEntity.created(showURI.toUri()).build();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param serviceCatalogs
     * @param result
     * @return ResponseEntity
     */
    @PostMapping(value = "/batch", name = "createBatch")
    public ResponseEntity<?> ServiceCatalogsCollectionJsonController.createBatch(@Valid @RequestBody Collection<ServiceCatalog> serviceCatalogs, BindingResult result) {
        
        if (result.hasErrors()) {
            return ResponseEntity.status(HttpStatus.CONFLICT).body(result);
        }
        
        getServiceCatalogService().save(serviceCatalogs);
        
        return ResponseEntity.created(listURI().toUri()).build();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param serviceCatalogs
     * @param result
     * @return ResponseEntity
     */
    @PutMapping(value = "/batch", name = "updateBatch")
    public ResponseEntity<?> ServiceCatalogsCollectionJsonController.updateBatch(@Valid @RequestBody Collection<ServiceCatalog> serviceCatalogs, BindingResult result) {
        
        if (result.hasErrors()) {
            return ResponseEntity.status(HttpStatus.CONFLICT).body(result);
        }
        
        getServiceCatalogService().save(serviceCatalogs);
        
        return ResponseEntity.ok().build();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param ids
     * @return ResponseEntity
     */
    @DeleteMapping(value = "/batch/{ids}", name = "deleteBatch")
    public ResponseEntity<?> ServiceCatalogsCollectionJsonController.deleteBatch(@PathVariable("ids") Collection<Long> ids) {
        
        getServiceCatalogService().delete(ids);
        
        return ResponseEntity.ok().build();
    }
    
}
