// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ocmms.cmms.web;

import com.ocmms.cmms.model.mm.storage.Warehouse;
import com.ocmms.cmms.service.api.WarehouseService;
import com.ocmms.cmms.web.WarehousesCollectionJsonController;
import com.ocmms.cmms.web.WarehousesItemJsonController;
import io.springlets.data.domain.GlobalSearch;
import java.util.Collection;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.mvc.method.annotation.MvcUriComponentsBuilder;
import org.springframework.web.util.UriComponents;

privileged aspect WarehousesCollectionJsonController_Roo_JSON {
    
    declare @type: WarehousesCollectionJsonController: @RestController;
    
    declare @type: WarehousesCollectionJsonController: @RequestMapping(value = "/api/warehouses", name = "WarehousesCollectionJsonController", produces = MediaType.APPLICATION_JSON_VALUE);
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private WarehouseService WarehousesCollectionJsonController.warehouseService;
    
    /**
     * TODO Auto-generated constructor documentation
     * 
     * @param warehouseService
     */
    @Autowired
    public WarehousesCollectionJsonController.new(WarehouseService warehouseService) {
        this.warehouseService = warehouseService;
    }

    /**
     * TODO Auto-generated method documentation
     * 
     * @return WarehouseService
     */
    public WarehouseService WarehousesCollectionJsonController.getWarehouseService() {
        return warehouseService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param warehouseService
     */
    public void WarehousesCollectionJsonController.setWarehouseService(WarehouseService warehouseService) {
        this.warehouseService = warehouseService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param globalSearch
     * @param pageable
     * @return ResponseEntity
     */
    @GetMapping(name = "list")
    public ResponseEntity<Page<Warehouse>> WarehousesCollectionJsonController.list(GlobalSearch globalSearch, Pageable pageable) {
        
        Page<Warehouse> warehouses = getWarehouseService().findAll(globalSearch, pageable);
        return ResponseEntity.ok(warehouses);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return UriComponents
     */
    public static UriComponents WarehousesCollectionJsonController.listURI() {
        return MvcUriComponentsBuilder
            .fromMethodCall(
                MvcUriComponentsBuilder.on(WarehousesCollectionJsonController.class).list(null, null))
            .build().encode();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param warehouse
     * @param result
     * @return ResponseEntity
     */
    @PostMapping(name = "create")
    public ResponseEntity<?> WarehousesCollectionJsonController.create(@Valid @RequestBody Warehouse warehouse, BindingResult result) {
        
        if (warehouse.getId() != null || warehouse.getVersion() != null) {        
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
        
        if (result.hasErrors()) {
            return ResponseEntity.status(HttpStatus.CONFLICT).body(result);
        }
        
        Warehouse newWarehouse = getWarehouseService().save(warehouse);
        UriComponents showURI = WarehousesItemJsonController.showURI(newWarehouse);
        
        return ResponseEntity.created(showURI.toUri()).build();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param warehouses
     * @param result
     * @return ResponseEntity
     */
    @PostMapping(value = "/batch", name = "createBatch")
    public ResponseEntity<?> WarehousesCollectionJsonController.createBatch(@Valid @RequestBody Collection<Warehouse> warehouses, BindingResult result) {
        
        if (result.hasErrors()) {
            return ResponseEntity.status(HttpStatus.CONFLICT).body(result);
        }
        
        getWarehouseService().save(warehouses);
        
        return ResponseEntity.created(listURI().toUri()).build();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param warehouses
     * @param result
     * @return ResponseEntity
     */
    @PutMapping(value = "/batch", name = "updateBatch")
    public ResponseEntity<?> WarehousesCollectionJsonController.updateBatch(@Valid @RequestBody Collection<Warehouse> warehouses, BindingResult result) {
        
        if (result.hasErrors()) {
            return ResponseEntity.status(HttpStatus.CONFLICT).body(result);
        }
        
        getWarehouseService().save(warehouses);
        
        return ResponseEntity.ok().build();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param ids
     * @return ResponseEntity
     */
    @DeleteMapping(value = "/batch/{ids}", name = "deleteBatch")
    public ResponseEntity<?> WarehousesCollectionJsonController.deleteBatch(@PathVariable("ids") Collection<Long> ids) {
        
        getWarehouseService().delete(ids);
        
        return ResponseEntity.ok().build();
    }
    
}
