// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ocmms.cmms.web;

import com.ocmms.cmms.web.WorkCenterResponsiblesItemHierarchyWorkCentersThymeleafController;
import com.ocmms.cmms.web.WorkCenterResponsiblesItemHierarchyWorkCentersThymeleafLinkFactory;
import io.springlets.web.mvc.util.MethodLinkFactory;
import io.springlets.web.mvc.util.SpringletsMvcUriComponentsBuilder;
import java.util.Map;
import org.springframework.stereotype.Component;
import org.springframework.web.util.UriComponents;

privileged aspect WorkCenterResponsiblesItemHierarchyWorkCentersThymeleafLinkFactory_Roo_LinkFactory {
    
    declare parents: WorkCenterResponsiblesItemHierarchyWorkCentersThymeleafLinkFactory implements MethodLinkFactory<WorkCenterResponsiblesItemHierarchyWorkCentersThymeleafController>;
    
    declare @type: WorkCenterResponsiblesItemHierarchyWorkCentersThymeleafLinkFactory: @Component;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String WorkCenterResponsiblesItemHierarchyWorkCentersThymeleafLinkFactory.DATATABLES = "datatables";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String WorkCenterResponsiblesItemHierarchyWorkCentersThymeleafLinkFactory.DATATABLESBYIDSIN = "datatablesByIdsIn";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String WorkCenterResponsiblesItemHierarchyWorkCentersThymeleafLinkFactory.CREATEFORM = "createForm";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String WorkCenterResponsiblesItemHierarchyWorkCentersThymeleafLinkFactory.REMOVEFROMHIERARCHYWORKCENTERS = "removeFromHierarchyWorkCenters";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String WorkCenterResponsiblesItemHierarchyWorkCentersThymeleafLinkFactory.REMOVEFROMHIERARCHYWORKCENTERSBATCH = "removeFromHierarchyWorkCentersBatch";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String WorkCenterResponsiblesItemHierarchyWorkCentersThymeleafLinkFactory.CREATE = "create";
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Class
     */
    public Class<WorkCenterResponsiblesItemHierarchyWorkCentersThymeleafController> WorkCenterResponsiblesItemHierarchyWorkCentersThymeleafLinkFactory.getControllerClass() {
        return WorkCenterResponsiblesItemHierarchyWorkCentersThymeleafController.class;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param methodName
     * @param parameters
     * @param pathVariables
     * @return UriComponents
     */
    public UriComponents WorkCenterResponsiblesItemHierarchyWorkCentersThymeleafLinkFactory.toUri(String methodName, Object[] parameters, Map<String, Object> pathVariables) {
        if (methodName.equals(DATATABLES)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).datatables(null, null, null, null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(DATATABLESBYIDSIN)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).datatablesByIdsIn(null, null, null, null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(CREATEFORM)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).createForm(null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(REMOVEFROMHIERARCHYWORKCENTERS)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).removeFromHierarchyWorkCenters(null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(REMOVEFROMHIERARCHYWORKCENTERSBATCH)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).removeFromHierarchyWorkCentersBatch(null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(CREATE)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).create(null, null, null, null, null)).buildAndExpand(pathVariables);
        }
        throw new IllegalArgumentException("Invalid method name: " + methodName);
    }
    
}
