net.sf.jasperreports.extension.registry.factory.simple.font.families=net.sf.jasperreports.engine.fonts.SimpleFontExtensionsRegistryFactory
#net.sf.jasperreports.extension.simple.font.families.lobstertwo=fonts/fonts.xml
net.sf.jasperreports.awt.ignore.missing.font=true
net.sf.jasperreports.extension.simple.font.families.dejavu=fonts/fonts.xml
date.format=dd-MM-yyyy 
datetime.format=dd-MM-yyyy HH:mm:ss 
calendar.date.format=dd-mm-yyyy 
calendar.datetime.format=dd-mm-yyyy HH:mm:ss